language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
script:
  - npm install
  - npm run test
deploy:
  provider: heroku
  app: chat-api
  api_key:
    secure: "5e9215eb-51a5-4818-a75c-2267146eef50"
    on:
    branch: master
